version: '3.8'

services:
  my_gradio_app:
    build: .
    image: galicca-app:env1
    environment:
      - GRADIO_SERVER_NAME=0.0.0.0
      - GRADIO_SERVER_PORT=7860
      - SHELL=/bin/bash  # Set the SHELL environment variable
    ports:
      - "7860:7860" # Open port
      - "8888:8888"
    volumes: 
      - ./Gallica_App:/root/Gallica_App
    runtime: nvidia  # Use NVIDIA Container Toolkit
    # Jupyter and Gradio are running
    command: /bin/bash -c "jupyter lab --ip='0.0.0.0' --port=8888 --no-browser --allow-root"
    deploy:   
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: 1
            capabilities: [gpu]
volumes:
  Gallica_App:

