version: '3.8'

services:
  my_gradio_app:
    build: .
    image: galicca-app:env1
    environment:
      - GRADIO_SERVER_NAME=0.0.0.0
      - GRADIO_SERVER_PORT=7860
    ports:
      - "7860:7860" # Open port
      - "8888:8888"
    volumes: 
      - ./data:/Gallica_App # Mount the current directory on your computer to /workdir in the container , chan 
    runtime: nvidia  # Use NVIDIA Container Toolkit
    command: /bin/bash -c "jupyter lab --ip='0.0.0.0' --port=8888 --no-browser --allow-root & python3 Gallica_App/src/test/test_app.py"
    deploy:   
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: 1
            capabilities: [gpu]


