version: '3.8'

services:
  my_gradio_app:
    build: .
    image: galicca-app:env1
    environment:
      - GRADIO_SERVER_NAME=0.0.0.0
      - GRADIO_SERVER_PORT=7860
    ports:
      - "7860:7860" # Open port
    volumes: 
      - ./data:/workdir/data # Mount the current directory on your computer to /workdir in the container , chan 
    command: ["python3", "test_requirements.py"]  # Replace with your actual script filename
    runtime: nvidia  # Use NVIDIA Container Toolkit

    #specific and limited deployment
    deploy:   
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: 1
            capabilities: [gpu]

